name: Pylint

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d
        
    - name: Vermin
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run vermin
        
    - name: Pylint
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run pylint
